"""Mock AI Provider simulating Hunyuan 3D + Meshy + Godot pipeline scenarios."""

import asyncio
from typing import AsyncGenerator, List
from rigmate.core.quota import QuotaSnapshot, TokenUsage
from rigmate.providers.base import BaseAIProvider, BaseQuotaProvider, ChatMessage, ProviderResponse


class MockAIProvider(BaseAIProvider, BaseQuotaProvider):
    """
    Simulated AI provider for local testing without Blender or Antigravity CLI.
    Supports contextual scenario responses based on user queries.
    """

    def __init__(self, model: str = "mock-hunyuan-assistant-v1"):
        self._model = model

    @property
    def provider_id(self) -> str:
        return "mock"

    @property
    def model_name(self) -> str:
        return self._model

    async def generate_response(
        self,
        messages: List[ChatMessage],
        session_id: str,
        timeout_seconds: float = 30.0,
    ) -> ProviderResponse:
        await asyncio.sleep(0.2)  # Simulate network latency

        last_user_msg = ""
        for m in reversed(messages):
            if m.role == "user":
                last_user_msg = m.content.lower()
                break

        # Context-aware mock responses
        if any(k in last_user_msg for k in ["diagnose", "check", "inspect", "kiểm tra", "chẩn đoán"]):
            resp_text = (
                "[Mock Analysis] Inspected character model in Scene:\n"
                "- Detected Hunyuan 3D Mesh (~52,400 vertices): Dense vertex topology. "
                "Recommend 40-50% Decimation if targeting real-time Godot gameplay.\n"
                "- Meshy Armature: 52 bones detected. Individual finger chains not detected "
                "(common for mitten-hand meshes).\n"
                "- Recommend applying all transforms (Ctrl+A) before adjusting vertex weights."
            )
            actions = ["Apply Transforms", "Check Weights", "Add Fingers"]
        elif any(k in last_user_msg for k in ["finger", "hand", "ngón", "tay"]):
            resp_text = (
                "[Mock Finger Guide] Finger articulation analysis:\n"
                "Models generated by Hunyuan 3D often have fused fingers. Meshy auto-rig binds to wrist/hand bones. "
                "In upcoming versions, RigMate provides automated finger chain generation matched to hand bounds."
            )
            actions = ["Generate Finger Bones", "View Topology Guide"]
        elif any(k in last_user_msg for k in ["godot", "export", "gltf"]):
            resp_text = (
                "[Mock Godot Guide] Godot Engine export recommendations:\n"
                "1. Preferred format: glTF 2.0 (.glb) or .tscn.\n"
                "2. Bone influence limit: Godot defaults to 4 weights per vertex (can enable 8 in Project Settings).\n"
                "3. Ensure root bone (e.g. Hips or Root) is properly configured for AnimationTree."
            )
            actions = ["Verify glTF Compatibility", "Optimize for Godot"]
        else:
            resp_text = (
                f"[Mock Provider] RigMate received query: '{last_user_msg}'. "
                "Operating under Mock Provider mode (ideal for development without live Antigravity CLI)."
            )
            actions = ["Diagnose Rig", "Godot Export Prep"]

        token_usage = TokenUsage.create(
            prompt=len(last_user_msg) // 3 + 20,
            completion=len(resp_text) // 3,
        )

        return ProviderResponse(
            text=resp_text,
            token_usage=token_usage,
            suggested_actions=actions,
            raw_metadata={"mode": "mock", "session_id": session_id},
        )

    async def stream_response(
        self,
        messages: List[ChatMessage],
        session_id: str,
    ) -> AsyncGenerator[str, None]:
        full_resp = await self.generate_response(messages, session_id)
        words = full_resp.text.split(" ")
        for w in words:
            yield w + " "
            await asyncio.sleep(0.03)

    async def fetch_quota_snapshot(self, account_profile: str = "default") -> QuotaSnapshot:
        """Return simulated quota snapshot explicitly tagged as DEMO."""
        return QuotaSnapshot(
            provider_name="MockProvider",
            model_name=self._model,
            account_profile=account_profile,
            source="DEMO",
            quota_remaining=75.0,
            quota_total=100.0,
            quota_unit="requests",
            reset_at="2026-09-18T00:00:00Z",
            plan_expiration="2026-10-01T00:00:00Z",
        )
